from prompt_engineering_methods.one_shot import generate_response_one_shot

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
import gradio as gr

def generate_response(prompt_txt):
    return generate_response_one_shot(prompt_txt)


chat_application = gr.Interface(
    fn=generate_response,
    inputs=gr.Textbox(label="Input", lines=2, placeholder="Type your question here..."),
    outputs=gr.Textbox(label="Output"),
    title="Chatbot",
    description="Ask any question and the chatbot will try to answer."
)

if __name__ == "__main__":
    chat_application.launch(
        server_name="127.0.0.1", 
        server_port=7861, 
        share=True, 
        debug=True, 
        inbrowser=True
    )